// Generated by gencpp from file bwi_msgs/LEDStatus.msg
// DO NOT EDIT!


#ifndef BWI_MSGS_MESSAGE_LEDSTATUS_H
#define BWI_MSGS_MESSAGE_LEDSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bwi_msgs
{
template <class ContainerAllocator>
struct LEDStatus_
{
  typedef LEDStatus_<ContainerAllocator> Type;

  LEDStatus_()
    : status(0)  {
    }
  LEDStatus_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;



  enum {
    RUN_ON = 1u,
    RUN_OFF = 0u,
    CAMERA_ON = 3u,
    CAMERA_OFF = 2u,
  };


  typedef boost::shared_ptr< ::bwi_msgs::LEDStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bwi_msgs::LEDStatus_<ContainerAllocator> const> ConstPtr;

}; // struct LEDStatus_

typedef ::bwi_msgs::LEDStatus_<std::allocator<void> > LEDStatus;

typedef boost::shared_ptr< ::bwi_msgs::LEDStatus > LEDStatusPtr;
typedef boost::shared_ptr< ::bwi_msgs::LEDStatus const> LEDStatusConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bwi_msgs::LEDStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bwi_msgs::LEDStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bwi_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'bwi_msgs': ['/home/yohei/rl_ws/src/bwi_common/bwi_msgs/msg', '/home/yohei/rl_ws/devel/.private/bwi_msgs/share/bwi_msgs/msg'], 'bwi_planning_common': ['/home/yohei/rl_ws/src/bwi_common/bwi_planning_common/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::LEDStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bwi_msgs::LEDStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::LEDStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bwi_msgs::LEDStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::LEDStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bwi_msgs::LEDStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bwi_msgs::LEDStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca10aeadc7986827cb9450ebce4e4963";
  }

  static const char* value(const ::bwi_msgs::LEDStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca10aeadc7986827ULL;
  static const uint64_t static_value2 = 0xcb9450ebce4e4963ULL;
};

template<class ContainerAllocator>
struct DataType< ::bwi_msgs::LEDStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bwi_msgs/LEDStatus";
  }

  static const char* value(const ::bwi_msgs::LEDStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bwi_msgs::LEDStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# LED Status\n\
\n\
# Service Variables\n\
uint8 RUN_ON = 1\n\
uint8 RUN_OFF = 0\n\
uint8 CAMERA_ON = 3\n\
uint8 CAMERA_OFF = 2\n\
\n\
# Selects which animation to execute\n\
\n\
uint8 status\n\
";
  }

  static const char* value(const ::bwi_msgs::LEDStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bwi_msgs::LEDStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LEDStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bwi_msgs::LEDStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bwi_msgs::LEDStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BWI_MSGS_MESSAGE_LEDSTATUS_H
