; Auto-generated. Do not edit!


(cl:in-package bwi_msgs-msg)


;//! \htmlinclude LogicalActionFeedback.msg.html

(cl:defclass <LogicalActionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass LogicalActionFeedback (<LogicalActionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <LogicalActionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'LogicalActionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name bwi_msgs-msg:<LogicalActionFeedback> is deprecated: use bwi_msgs-msg:LogicalActionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <LogicalActionFeedback>) ostream)
  "Serializes a message object of type '<LogicalActionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <LogicalActionFeedback>) istream)
  "Deserializes a message object of type '<LogicalActionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<LogicalActionFeedback>)))
  "Returns string type for a message object of type '<LogicalActionFeedback>"
  "bwi_msgs/LogicalActionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'LogicalActionFeedback)))
  "Returns string type for a message object of type 'LogicalActionFeedback"
  "bwi_msgs/LogicalActionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<LogicalActionFeedback>)))
  "Returns md5sum for a message object of type '<LogicalActionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'LogicalActionFeedback)))
  "Returns md5sum for a message object of type 'LogicalActionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<LogicalActionFeedback>)))
  "Returns full string definition for message of type '<LogicalActionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'LogicalActionFeedback)))
  "Returns full string definition for message of type 'LogicalActionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <LogicalActionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <LogicalActionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'LogicalActionFeedback
))
