// Generated by gencpp from file plan_execution/GetHriMessageResponse.msg
// DO NOT EDIT!


#ifndef PLAN_EXECUTION_MESSAGE_GETHRIMESSAGERESPONSE_H
#define PLAN_EXECUTION_MESSAGE_GETHRIMESSAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <plan_execution/HriMessage.h>

namespace plan_execution
{
template <class ContainerAllocator>
struct GetHriMessageResponse_
{
  typedef GetHriMessageResponse_<ContainerAllocator> Type;

  GetHriMessageResponse_()
    : message()  {
    }
  GetHriMessageResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::plan_execution::HriMessage_<ContainerAllocator>  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetHriMessageResponse_

typedef ::plan_execution::GetHriMessageResponse_<std::allocator<void> > GetHriMessageResponse;

typedef boost::shared_ptr< ::plan_execution::GetHriMessageResponse > GetHriMessageResponsePtr;
typedef boost::shared_ptr< ::plan_execution::GetHriMessageResponse const> GetHriMessageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_execution::GetHriMessageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace plan_execution

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'plan_execution': ['/home/yohei/rl_ws/src/bwi_common/plan_execution/msg', '/home/yohei/rl_ws/devel/.private/plan_execution/share/plan_execution/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "79a5f3df63f78ac18c5bf2f132803ded";
  }

  static const char* value(const ::plan_execution::GetHriMessageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x79a5f3df63f78ac1ULL;
  static const uint64_t static_value2 = 0x8c5bf2f132803dedULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_execution/GetHriMessageResponse";
  }

  static const char* value(const ::plan_execution::GetHriMessageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "HriMessage message\n\
\n\
================================================================================\n\
MSG: plan_execution/HriMessage\n\
string id\n\
string content\n\
string from\n\
string to\n\
";
  }

  static const char* value(const ::plan_execution::GetHriMessageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetHriMessageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_execution::GetHriMessageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plan_execution::GetHriMessageResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    s << std::endl;
    Printer< ::plan_execution::HriMessage_<ContainerAllocator> >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_EXECUTION_MESSAGE_GETHRIMESSAGERESPONSE_H
