// Generated by gencpp from file plan_execution/UpdateFluentsResponse.msg
// DO NOT EDIT!


#ifndef PLAN_EXECUTION_MESSAGE_UPDATEFLUENTSRESPONSE_H
#define PLAN_EXECUTION_MESSAGE_UPDATEFLUENTSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace plan_execution
{
template <class ContainerAllocator>
struct UpdateFluentsResponse_
{
  typedef UpdateFluentsResponse_<ContainerAllocator> Type;

  UpdateFluentsResponse_()
    : consistent(false)  {
    }
  UpdateFluentsResponse_(const ContainerAllocator& _alloc)
    : consistent(false)  {
  (void)_alloc;
    }



   typedef uint8_t _consistent_type;
  _consistent_type consistent;





  typedef boost::shared_ptr< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct UpdateFluentsResponse_

typedef ::plan_execution::UpdateFluentsResponse_<std::allocator<void> > UpdateFluentsResponse;

typedef boost::shared_ptr< ::plan_execution::UpdateFluentsResponse > UpdateFluentsResponsePtr;
typedef boost::shared_ptr< ::plan_execution::UpdateFluentsResponse const> UpdateFluentsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace plan_execution

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'plan_execution': ['/home/yohei/rl_ws/src/bwi_common/plan_execution/msg', '/home/yohei/rl_ws/devel/.private/plan_execution/share/plan_execution/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be6162d8a10e4281ea405616a9216683";
  }

  static const char* value(const ::plan_execution::UpdateFluentsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe6162d8a10e4281ULL;
  static const uint64_t static_value2 = 0xea405616a9216683ULL;
};

template<class ContainerAllocator>
struct DataType< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "plan_execution/UpdateFluentsResponse";
  }

  static const char* value(const ::plan_execution::UpdateFluentsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool consistent\n\
\n\
";
  }

  static const char* value(const ::plan_execution::UpdateFluentsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.consistent);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UpdateFluentsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::plan_execution::UpdateFluentsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::plan_execution::UpdateFluentsResponse_<ContainerAllocator>& v)
  {
    s << indent << "consistent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.consistent);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAN_EXECUTION_MESSAGE_UPDATEFLUENTSRESPONSE_H
